services:
  backend:
    build: backend
    ports:
      - 3000:3000
    secrets:
      - db-password
    environment:
      MYSQL_HOST: db
    networks:
      - backend-db
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
  db:
    build: db
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-pdb-57xsl"]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-db
volumes:
  db-data: {}
secrets:
  db-password:
    file: db/password.txt
networks:
  backend-db: {}
