services:
  backend:
    build: backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    environment:
      TZ: Asia/Tokyo
    networks:
      - backend-db
    depends_on:
      - db
    volumes:
      - ./backend:/myapp
  db:
    build: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db-data:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
    networks:
      - backend-db
volumes:
  db-data: {}
networks:
  backend-db: {}
